var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/register/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__ce313ce4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_4b63a0e1._.js")
R.c("server/chunks/ssr/_3b0d5b48._.js")
R.c("server/chunks/ssr/[root-of-the-server]__27bda8b8._.js")
R.c("server/chunks/ssr/node_modules_next_dist_compiled_@opentelemetry_api_index_d03d2993.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_cc94c707._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/[root-of-the-server]__11fa4345._.js")
R.c("server/chunks/ssr/src_app_not-found_tsx_3f23d179._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_2fffaa3a._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_next-internal_server_app_register_page_actions_cf89a161.js")
R.m(63288)
module.exports=R.m(63288).exports
